networks:
  backend:
    name: backend

services:
  nginx-modsec:
    build: ./nginx-modsec
    container_name: nginx-modsec
    env_file: .env
    depends_on:
      - django
    networks:
      - backend
    ports:
      - "8080:8080"
      - "8443:8443"

  django:
    build: ./django
    container_name: django
    env_file: .env
    networks:
      - backend
    volumes:
      - ./django/accounts:/django/accounts
      - ./django/pong:/django/pong
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build: ./postgres
    container_name: postgres
    env_file: .env
    networks:
      - backend
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg-data:
    name: pg-data