FROM prom/prometheus:v2.52.0

COPY prometheus.yml /etc/prometheus/prometheus.yml


# COPY postgres_alerts.yml /etc/prometheus/postgres_alerts.yml





EXPOSE 9090





# COPY prometheus.yml /prometheus/prometheus.yml
