global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets:
        - django:8000
        labels:
          group: 'django-app'
  - job_name: 'postgres'
    static_configs:
      - targets:
        - postgres_exporter:9187
        labels:
          group: 'postgres-server'
  