{
 "title": "NGINX ModSecurity OWASP CRS V0.0",
 "description": "Dashboard to work with ModSecurity and the OWASP Coreruleset.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "cloud,wiki,grafana,shop,mineos,sonarr,radarr,gitea,mountaineering,heimdall,yurt"
   },
   { "name": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Top Attackers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{job=\"nginx_error\", __name__=\"sum \"}"
    }
   ]
  },
  {
   "title": "ModSec Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"nginx_error\", __name__=\"sum \"}"
    },
    {
     "expr": "{job=\"nginx_error\", __name__=\"sum \"}"
    }
   ]
  },
  {
   "title": "RuleId's at Vhost",
   "type": "stat",
   "gridPos": { "h": 22, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{job=\"nginx_error\", __name__=\"sum \"}"
    }
   ]
  },
  {
   "title": "Error Logs  ➡️ only ModSecurity",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"nginx_error\"}|= \"$service\" |= \"ModSecurity\" |= \"coreruleset\" | pattern \"<date> <time> [<level>] <_> ModSecurity: <modsec_action> [file \\\"/usr/local/etc/modsecurity/coreruleset/rules/<rule_set>.conf<_> [id \\\"<rule_id>\\\"<_> [msg \\\"<msg>\\\"] <_>[ver \\\"<owasp_version>\\\"]<_>] [tag <tags>] [host<_>, client: <client>, server: <server>, request: \\\"<request_method> <ressource> <http_version>\\\", <_>\"\n\n| line_format \"?️ {{.date}} {{.time}} ? {{.server}} {{.request_method}} {{.ressource}} ❗️☠️ {{.client}} ☠️️❗️ \\n➡️ RuleSet: {{.rule_set}} RuleId: {{.rule_id}} {{.msg}}\\n?️ [tag {{.tags}}]\""
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Exact Rule Infos",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{job=\"nginx_error\", __name__=\" \"}"
    }
   ]
  },
  {
   "title": "Error Logs all",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{job=\"nginx_error\"}"
    }
   ]
  }
 ]
}