# Generated by Django 5.0.6 on 2024-07-12 11:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_profile_blocked_profiles_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('message', models.TextField(null=True, verbose_name='message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_messages', to='profiles.profile', verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_messages', to='profiles.profile', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'friend message',
                'verbose_name_plural': 'friend messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='profiles.profile', verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='profiles.profile', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'friend request',
                'verbose_name_plural': 'friend requests',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_profile1', to='profiles.profile', verbose_name='profile1')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_profile2', to='profiles.profile', verbose_name='profile2')),
            ],
            options={
                'verbose_name': 'friendship',
                'verbose_name_plural': 'friendships',
                'unique_together': {('profile1', 'profile2')},
            },
        ),
    ]
