global:
  scrape_interval: 15s

rule_files:
  - 'postgres_alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alert-manager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets:
        - django:8000
        labels:
          group: 'django-app'
  - job_name: 'postgres-exporter'
    static_configs:
      - targets:
        - postgres-exporter:9187
        # labels:
        #   group: 'postgres-server'


