# Generated by Django 5.0.6 on 2024-07-22 15:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('player_limit', models.PositiveSmallIntegerField(default=1, verbose_name='player limit')),
                ('win_score', models.PositiveSmallIntegerField(default=5, verbose_name='score to win')),
                ('current_order', models.PositiveSmallIntegerField(default=0, verbose_name='current order')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_received', to='profiles.profile', verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent', to='profiles.profile', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'game invitation',
                'verbose_name_plural': 'game invitations',
            },
        ),
        migrations.CreateModel(
            name='GameMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='games.game', verbose_name='game')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent', to='profiles.profile', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'game message',
                'verbose_name_plural': 'game messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Ready', 'Ready'), ('Playing', 'Playing'), ('Watching', 'Watching')], default='Waiting', max_length=10, verbose_name='status')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='game')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='games.player', verbose_name='winner'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('started', models.BooleanField(default=False, verbose_name='started')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='game')),
                ('next_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_rounds', to='games.round', verbose_name='next round')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_rounds', to='games.player', verbose_name='player1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_rounds', to='games.player', verbose_name='player2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='games.player', verbose_name='winner')),
            ],
            options={
                'verbose_name': 'round',
                'verbose_name_plural': 'rounds',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='points')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
            },
        ),
        migrations.AddConstraint(
            model_name='gameinvite',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_game_invite_pair'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('game', 'player')},
        ),
    ]
