# Generated by Django 5.1 on 2024-09-18 09:39

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('player_limit', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('win_score', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('ball_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium')),
                ('ball_speed', models.CharField(choices=[('Slow', 'Slow'), ('Normal', 'Normal'), ('Fast', 'Fast')], default='Normal')),
                ('paddle_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium')),
                ('ai_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard')], default='Normal')),
                ('map_choice', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('power_ups', models.CharField(blank=True, max_length=255, null=True)),
                ('game_events', models.CharField(blank=True, max_length=255, null=True)),
                ('current_order', models.IntegerField(default=-1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'game invitation',
                'verbose_name_plural': 'game invitations',
            },
        ),
        migrations.CreateModel(
            name='GameMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Send', 'Send'), ('Join', 'Join'), ('Leave', 'Leave'), ('Prepare', 'Prepare'), ('Eliminate', 'Eliminate'), ('Win', 'Win')], default='Send', max_length=20)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'game message',
                'verbose_name_plural': 'game messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('score1', models.PositiveSmallIntegerField(default=0)),
                ('score2', models.PositiveSmallIntegerField(default=0)),
                ('elo_win', models.IntegerField(default=0)),
                ('elo_lose', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'game round',
                'verbose_name_plural': 'game rounds',
            },
        ),
    ]
