# Generated by Django 5.1 on 2024-09-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_game', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_received', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='gamemessage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='games.game'),
        ),
        migrations.AddField(
            model_name='gamemessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_messages_sent', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_rounds', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_rounds', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_won', to='profiles.profile'),
        ),
        migrations.AddConstraint(
            model_name='gameinvite',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_game_invite_pair'),
        ),
    ]
