apiVersion: 1
groups:
    - orgId: 1
      name: test_group
      folder: test_folder
      interval: 10s
      rules:
        - uid: edtib9ciymi9sa
          title: test-dja
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: builder
                expr: count(django_http_requests_total_by_method_total{job="django"})
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: O6v4rMpizda
          panelId: 15
          noDataState: NoData
          execErrState: Error
          for: 10s
          annotations:
            __dashboardUid__: O6v4rMpizda
            __panelId__: "15"
          labels: {}
          isPaused: false
