apiVersion: 1
groups:
    - orgId: 1
      name: 4|5 responses
      folder: Django
      interval: 5m
      rules:
        - uid: ady9p1inmrwn4d
          title: Response Status
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                disableTextWrap: false
                editorMode: code
                expr: sum(rate(django_http_responses_total_by_status_view_method_total{status=~"4..|5.."}[$__rate_interval])) by (namespace, job, app, instance, view, method, status)
                format: time_series
                fullMetaSearch: false
                includeNullMetadata: true
                instant: false
                interval: ""
                intervalFactor: 1
                intervalMs: 15000
                legendFormat: status={{status}}, method={{method}}, view={{view}}
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: O6v4rMpizda2
          panelId: 11
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: O6v4rMpizda2
            __panelId__: "11"
          labels:
            method: '{{method}}'
            status: '{{status}}'
            view: '{{view}}'
          isPaused: false
