apiVersion: 1
groups:
    - orgId: 1
      name: 4-5xx responses
      folder: Django
      interval: 5m
      rules:
        - uid: edxzamsdkv4e8e
          title: 4XX Responses
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: sum(irate(django_http_responses_total_by_status_total{status=~"4.+",app=~"^()$"}[$__rate_interval]))
                format: time_series
                interval: ""
                intervalFactor: 1
                intervalMs: 30000
                legendFormat: ""
                maxDataPoints: 100
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: min
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: O6v4rMpizda2
          panelId: 16
          noDataState: OK
          execErrState: OK
          for: 5m
          annotations:
            __dashboardUid__: O6v4rMpizda2
            __panelId__: "16"
          labels: {}
          isPaused: false
        - uid: adxzar3hmdjwge
          title: 5XX Responses
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: sum(irate(django_http_responses_total_by_status_total{status=~"5.+",app=~"^()$"}[$__rate_interval]))
                format: time_series
                interval: ""
                intervalFactor: 1
                intervalMs: 15000
                legendFormat: ""
                maxDataPoints: 100
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: min
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: O6v4rMpizda2
          panelId: 17
          noDataState: OK
          execErrState: OK
          for: 5m
          annotations:
            __dashboardUid__: O6v4rMpizda2
            __panelId__: "17"
          labels: {}
          isPaused: false
