apiVersion: 1
groups:
    - orgId: 1
      name: testGroupCache
      folder: testFolderCache
      interval: 5m
      rules:
        - uid: fdtiu5iylbcaoc
          title: cacheratio
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: avg(rate(pg_stat_database_blks_hit{datname="postgres"}[5m]) / (rate(pg_stat_database_blks_hit{datname="postgres"}[5m]) + rate(pg_stat_database_blks_read{datname="postgres"}[5m]))) by (datname)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.98
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations: {}
          labels:
            receiver: Discord_grafana
          isPaused: false
