apiVersion: 1
groups:
    - orgId: 1
      name: django database
      folder: Django
      interval: 1m
      rules:
        - uid: edycwru7s6mm8b
          title: Migrations Unapplied
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: |-
                    max (
                      django_migrations_unapplied_total {
                          namespace="",
                          job=~"django"
                      }
                    ) by (namespace, job)
                    > 0
                instant: true
                interval: ""
                intervalMs: 15000
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: django-overview-jkwq
          panelId: 8
          noDataState: OK
          execErrState: OK
          for: 15m
          annotations:
            __dashboardUid__: django-overview-jkwq
            __panelId__: "8"
          isPaused: false
        - uid: cdycx2jshxvr4a
          title: Top Database Errors
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: "sum (\n  increase(\n    django_db_errors_total{\n      job=~\"django\",\n    }[10m]\n  )\n) by (type, namespace, job) \n> 0\n"
                format: table
                instant: true
                interval: ""
                intervalMs: 15000
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: django-overview-jkwq
          panelId: 9
          noDataState: OK
          execErrState: OK
          for: 15m
          annotations:
            __dashboardUid__: django-overview-jkwq
            __panelId__: "9"
          labels: {}
          isPaused: false
    - orgId: 1
      name: http responses
      folder: Django
      interval: 1m
      rules:
        - uid: ddycy3552nrb4f
          title: Response Status 4xx
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                disableTextWrap: false
                editorMode: code
                expr: |-
                    sum(rate(django_http_responses_total_by_status_view_method_total{status=~"^4.*"}[$__rate_interval])) by (namespace, job, app, instance, view, method, status)
                    /
                    sum(rate(django_http_responses_total_by_status_view_method_total[$__rate_interval])) by (namespace, job, app, instance, view, method, status)
                    * 100 > 5
                format: time_series
                fullMetaSearch: false
                includeNullMetadata: true
                instant: false
                interval: ""
                intervalFactor: 1
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: O6v4rMpizda2
          panelId: 39
          noDataState: OK
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: O6v4rMpizda2
            __panelId__: "39"
          labels: {}
          isPaused: false
        - uid: bdycy4swbpnuof
          title: Response Status 5xx
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                disableTextWrap: false
                editorMode: code
                expr: |-
                    sum(rate(django_http_responses_total_by_status_view_method_total{status=~"^5.*"}[$__rate_interval])) by (namespace, job, app, instance, view, method, status)
                    /
                    sum(rate(django_http_responses_total_by_status_view_method_total[$__rate_interval])) by (namespace, job, app, instance, view, method, status)
                    * 100 > 5
                format: time_series
                fullMetaSearch: false
                includeNullMetadata: true
                instant: false
                interval: ""
                intervalFactor: 1
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: O6v4rMpizda2
          panelId: 39
          noDataState: OK
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: O6v4rMpizda2
            __panelId__: "39"
          labels: {}
          isPaused: false
