FROM prometheuscommunity/postgres-exporter:v0.15.0


# COPY postgres_exporter.yml /postgres_exporter.yml
# COPY queries.yaml /etc/config/queries.yaml



# RUN /bin/postgres_exporter --collector.postmaster
# RUN /bin/postgres_exporter --extend.query-path=/etc/config/queries.yaml



EXPOSE 9187