# Example postgres_exporter configuration

# The address on which to expose the metrics and web interface
# web.listen-address: ":9187"

# DSN to connect to PostgreSQL.
# Replace <username>, <password>, <hostname>, <port>, and <database> with your specific PostgreSQL settings.
# data-source-name: "postgresql://<username>:<password>@<hostname>:<port>/<database>?sslmode=disable"

# data-source-name: "postgresql://user:password@postgresql:5432/db?sslmode=disable"
# data-source-name: "postgres://user:password@postgres:5432/db?sslmode=disable"

# data-source-name: "postgresql://user:password@localhost:5432/db?sslmode=disable"
# data-source-name: "postgres://user:password@localhost:5432/db?sslmode=disable"




# DSN for a second PostgreSQL database, if needed.
# Uncomment and replace with your second database settings if necessary.
# data-source-name-2: "postgresql://<username>:<password>@<hostname>:<port>/<database>?sslmode=disable"

# Add any additional custom queries you want to run.
# Replace <query_name> and <custom_sql_query> with your query name and SQL query.
# query_name: <custom_sql_query>

# Enable SSL for PostgreSQL connections if necessary.
# Uncomment if you need to enable SSL.
# ssl-mode: "disable"
# ssl-cert: "/path/to/ssl/cert"
# ssl-key: "/path/to/ssl/key"
# ssl-ca: "/path/to/ssl/ca"