# Generated by Django 5.0.6 on 2024-09-01 19:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Friend Request', 'Friend Request'), ('Friend Message', 'Friend Message'), ('Game Invitation', 'Game Invitation'), ('Game Message', 'Game Message')], default='Game Invitation', max_length=20)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_received', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['created_at'],
            },
        ),
    ]
