# Generated by Django 5.0.6 on 2024-07-22 15:28

import django.db.models.deletion
import django.utils.timezone
import profiles.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('alias', models.CharField(max_length=150, unique=True, verbose_name='alias')),
                ('avatar', models.ImageField(storage=profiles.storage.OverwriteStorage(), upload_to='avatars', verbose_name='avatar')),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Occupied', 'Occupied'), ('Disconnected', 'Disconnected')], default='Disconnected', verbose_name='status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='profiles.profile', verbose_name='blocked')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_profiles', to='profiles.profile', verbose_name='blocker')),
            ],
            options={
                'verbose_name': 'profile block',
                'verbose_name_plural': 'profile blocks',
            },
        ),
    ]
