# Generated by Django 5.0.6 on 2024-07-10 14:00

import django.db.models.deletion
import django.utils.timezone
import profiles.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('alias', models.CharField(max_length=150, unique=True, verbose_name='alias')),
                ('avatar', models.ImageField(storage=profiles.storage.OverwriteStorage(), upload_to='avatars', verbose_name='avatar')),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Occupied', 'Occupied'), ('Disconnected', 'Disconnected')], default='Disconnected', verbose_name='status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='profiles.profile', verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='profiles.profile', verbose_name='sender')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
