# Generated by Django 5.0.6 on 2024-09-01 19:32

import django.db.models.deletion
import django.utils.timezone
import profiles.models
import profiles.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alias', models.CharField(max_length=150, unique=True)),
                ('avatar', models.ImageField(null=True, storage=profiles.storage.OverwriteStorage(), upload_to=profiles.models.upload_avatar)),
                ('avatar_url', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Waiting', 'Waiting'), ('Playing', 'Playing'), ('Offline', 'Offline')], default='Offline')),
                ('default_lang', models.CharField(default='en', max_length=40)),
                ('elo', models.PositiveSmallIntegerField(default=1000)),
                ('is_ready', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_profiles', to='profiles.profile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_profiles', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'profile block',
                'verbose_name_plural': 'profile blocks',
            },
        ),
    ]
