# Generated by Django 5.0.6 on 2024-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_profiles',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='profiles.profile', verbose_name='blocked profiles'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
